export const USER_ROLES = {
  USER: 'USER',
  ADMIN: 'ADMIN',
  MODERATOR: 'MODERATOR'
};

export const VERIFICATION_LEVELS = {
  BASIC: 'BASIC',
  VERIFIED: 'VERIFIED',
  PREMIUM: 'PREMIUM'
};

export const PRODUCT_STATUS = {
  AVAILABLE: 'AVAILABLE',
  SOLD: 'SOLD',
  PENDING: 'PENDING',
  RESERVED: 'RESERVED'
};